### ISSUE TITLE
Stmcli date argument doesn't print the correct time

### ISSUE THREAD

**Issue by pgdagenais** [stmcli/stmcli#16]
For example when you use the -d tag: 

```
stmcli -s 51253 -b 435 -d 20160330
15:18
15:27
15:38
15:46
15:54
16:25
16:34
16:44
16:52
17:34
```

The last one is 17:34

But when you use the -d tag and the -t tag here is the result:

```
stmcli -s 51253 -b 435 -d 20160330 -t 17:00
17:02
17:16
17:34
17:58
18:25
18:52
19:20
```

It should show the 17:02 time instead of 17:34 on the first command

**Comment by pboardman** [comment]
Fixed in b3b40b2.
