### ISSUE TITLE
Convert all sqlite code to peewee.

### ISSUE THREAD

**Issue by pgdagenais** [stmcli/stmcli#27]
https://github.com/coleifer/peewee

**Comment by sapanshah** [comment]
I'd like to take this one on.

**Comment by kalkehcoisa** [comment]
Sending a pull request.
It would be good to organize some parts of the code and implement tests using tools like py.test. But, peewee is on. ;)

**Comment by pgdagenais** [comment]
Fixed with https://github.com/stmcli/stmcli/pull/28
