### ISSUE TITLE
Time issue near after 23:59

### ISSUE THREAD

**Issue by jingl3s** [stmcli/stmcli#30]
Version used: stmcli 1.0.3

When I use stmcli with a bus number, a bus stop with the next bus arrival are after 23h59, the time displayed are 24:XX and after 25:XX.

I have not search the source of issue for the moment. I will try a hard patch on my source code that use stmcli.

Example of output:
23:29
23:49
24:09
24:28
24:50
25:19
25:48

**Comment by jingl3s** [comment]
Ths issue is not from stmcli is from the STM GTFS data with invalid time after 23:59 where is can go to 26:XX.

**Comment by pboardman** [comment]
If I understand correctly it is suposed to be this way because a bus passing at 1AM (25:00) on nov 13 is still a 'day' bus from nov 12. I agree that it is a bit weird though
